name: Deploy Angular NX to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # ✅ Enables manual execution    

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v2
        with:
          version: 8.14.1
      - run: pnpm install --no-frozen-lockfile
        working-directory: mqml-frontend-workspace

      # - name: Install dependencies
      #   working-directory: ./mqml-frontedn-workspace/
      #   run: npm install --no-fund --no-audit

      # - name: Set up Nx workspace
      #   run: npx nx reset

      # Build Angular App with correct base href
      - name: Build Angular App
        run: pnpm nx build mqml-frontedn-workspace --no-cloud --base-href /mqml.diy/


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MQML_TOKEN }}
          publish_dir: dist/mqml-frontend-workspace
          cname: your-custom-domain.com # Remove or modify if not using a custom domain
