name: Deploy Angular NX to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # ✅ Enables manual execution    

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false


      - name: Show directory contents
        run: ls -lah ${{ github.workspace }}
    

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.1

          
      - name: install dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: mqml-frontend-workspace


      # Build Angular App with correct base href
      - name: Build Angular App
        working-directory: mqml-frontend-workspace
        run: pnpm nx build mqml-frontend-workspace --no-cloud --configuration=production --verbose



      # Deploy the Angular App to GitHub Pages
#      - name: Deploy to GitHub Pages
#        run: |
#          npx angular-cli-ghpages --dir=dist/apps/mqml-frontend-workspace
#        working-directory: mqml-frontend-workspace
#        env:
#          CI: true
#          GH_TOKEN: ${{ MQML_TOKEN }}


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MQML_SITE }}
          publish_dir: dist/mqml-frontend-workspace
          cname: your-custom-domain.com # Remove or modify if not using a custom domain
